# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
# Setup
title:               John Leung 
tagline:             'Data scientist / Particle phenomenologist'
description:         ''
#url:                 http://lanyon.getpoole.com
baseurl:             'bbsonjohn'
#plugins: [jekyll-paginate]
#paginate:            5
